---
name: ez_ticketz_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.0.2
  cupertino_icons: ^1.0.3
  time: ^2.0.0
  cached_network_image: ^3.0.0
  freezed_annotation: ^0.14.1
  google_fonts: ^2.0.0
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.14.0+3
  flutter_launcher_icons: ^0.9.0
  carousel_slider: ^3.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.0.1
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  build_runner: null
  effective_dart: ^1.3.1
flutter:
  uses-material-design: true
  assets:
  - assets/
flutter_icons:
  android: true
  ios: false
  image_path: assets/app_icon.png
