on:
  pull_request:
    branches:
      - master
    types: [ closed ]
    paths-ignore: ['doc/**','**.md','.gitignore','Prototype/**']

    workflow_dispatch:

name: Build Release APK
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: build-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Checkout Flutter Stable Channel
      uses: subosito/flutter-action@v1.5.1
      with:
        channel: 'stable'
    - name: Get Pub Dependencies
      run: flutter pub get
    - name: Run build runner for codegen files
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
    - name: Run Dart Analyzer
      run: flutter analyze .
    - name: Generate splitted release apks
      run: flutter build apk --target-platform android-arm,android-arm64 --obfuscate --split-debug-info=./ez_tickets_app/debug_trace
    - name: Bump version and push tag
      id: generate_tag
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor # major, minor, patch, false
        custom_release_rules: "chore:patch:Chore Tasks,hotfix:minor:Bug Fixes,refact:patch:Refactors,docs:patch:Documentation Changes,build:patch:Build System/Dependency Upgrades"
    - name: Upload release apk to artifacts
      uses: ncipollo/release-action@v1.8.6
      with:
        tag: "${{ steps.generate_tag.outputs.new_tag }}"
        artifacts: "build/app/outputs/apk/release/app-arm*.apk"
        name: "Release ${{ steps.generate_tag.outputs.new_tag }}"
        body: "${{ steps.generate_tag.outputs.changelog }}"
        token: ${{ secrets.EZ_TICKETS_APP_TOKEN }}
    - name: Upload apks to google drive
      uses: mkrakowitzer/actions-googledrive@1
      with:
        upload-from: ./build/app/outputs/apk/release/
        upload-to: APKS/ez_tickets_app/
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        google-client-id: ${{ secrets.DRIVE_CLIENT_ID }}
        google-client-secret: ${{ secrets.DRIVE_CLIENT_SECRET }}
        remove-outdated: 'false'
