name: Test PR
on: pull_request
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Checkout Flutter Stable Channel
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get Pub Dependencies
        run: flutter pub get
      - name: Run Dart Analyzer
        run: flutter analyze .
      - name: Generate release build
        run: flutter build apk --split-per-abi